# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#181818'
foreground = '#d4d4d4'

#[colors.cursor]
#cursor = '#d4d4d4'
#text = '#181818'

# Normal colors
[colors.normal]
black = '#131313'
red = '#ffcf5b'
green = '#7abf47'
yellow = '#ffcf5b'
blue = '#d4d4d4'
magenta = '#ffcf5b'
cyan = '#d4d4d4'
white = '#969696'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ffcf5b'
green = '#7abf47'
yellow = '#ffcf5b'
blue = '#d4d4d4'
magenta = '#ffcf5b'
cyan = '#d4d4d4'
white = '#d4d4d4'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#d4d4d4'

[[colors.indexed_colors]]
index = 17
color = '#f15050'

