# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#e7e7e7'
foreground = '#606060'

#[colors.cursor]
#cursor = '#606060'
#text = '#e7e7e7'

# Normal colors
[colors.normal]
black = '#eeeeee'
red = '#765b00'
green = '#53852f'
yellow = '#765b00'
blue = '#606060'
magenta = '#765b00'
cyan = '#606060'
white = '#888888'

# Bright colors
[colors.bright]
black = '#a1a6c5'
red = '#765b00'
green = '#53852f'
yellow = '#765b00'
blue = '#606060'
magenta = '#765b00'
cyan = '#606060'
white = '#606060'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#606060'

[[colors.indexed_colors]]
index = 17
color = '#c22727'

