attribute = { fg = "#d4d4d4" }
comment = { fg = "#a47e47", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#ffcf5b" }
constant = { fg = "#d4d4d4" }
"constant.builtin" = { fg = "#949cb1" }
"constant.builtin.boolean" = { fg = "#d4d4d4" }
"constant.character" = { fg = "#7abf47" }
"constant.character.escape" = { fg = "#ffcf5b" }
"constant.numeric" = { fg = "#d4d4d4" }
"constant.numeric.float" = { fg = "#d4d4d4" }
"constant.numeric.integer" = { fg = "#d4d4d4" }
constructor = { fg = "#94b0a6" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { fg = "#ffcf5b" }
"diff.delta.moved" = { fg = "#d4d4d4" }
"diff.minus" = { fg = "#e46565" }
"diff.plus" = { fg = "#82d458" }
error = { fg = "#f15050" }
function = { fg = "#d4d4d4" }
"function.builtin" = { fg = "#949cb1" }
"function.macro" = { fg = "#41a6b5" }
"function.method" = 
"function.special" = { fg = "#d4d4d4" }
hint = { fg = "#fef0ca" }
info = { fg = "#0db9d7" }
keyword = { fg = "#ffcf5b", modifiers = ["italic"] }
"keyword.control" = { fg = "#ffcf5b" }
"keyword.control.conditional" = { fg = "#ffcf5b" }
"keyword.control.exception" = { fg = "#ffcf5b" }
"keyword.control.repeat" = { fg = "#ffcf5b" }
"keyword.control.return" = { fg = "#ffcf5b", modifiers = ["italic"] }
"keyword.directive" = { fg = "#d4d4d4" }
"keyword.function" = { fg = "#ffcf5b" }
"keyword.operator" = { fg = "#ffcf5b" }
label = { fg = "#d4d4d4" }
"markup.bold" = { fg = "#d4d4d4", modifiers = ["bold"] }
"markup.heading" = 
"markup.heading.completion" = { bg = "#151515", fg = "#d4d4d4" }
"markup.heading.hover" = { bg = "#2e2e2e" }
"markup.italic" = { fg = "#d4d4d4", modifiers = ["italic"] }
"markup.link" = { fg = "#d4d4d4", underline = { style = "line" } }
"markup.link.label" = { fg = "#fef0ca" }
"markup.link.text" = { fg = "#fef0ca" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#d4d4d4", modifiers = ["bold"] }
"markup.normal.completion" = { fg = "#a47e47" }
"markup.normal.hover" = { fg = "#969696" }
"markup.raw" = { fg = "#fef0ca" }
"markup.raw.block" = { fg = "#fef0ca" }
"markup.raw.inline" = { bg = "#414868", fg = "#d4d4d4" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = 
operator = { fg = "#d4d4d4" }
special = { fg = "#949cb1" }
string = { fg = "#7abf47" }
"string.regexp" = { fg = "#b4f9f8" }
"string.special" = { fg = "#949cb1" }
tag = { fg = "#ffcf5b" }
type = { fg = "#94b0a6" }
"type.builtin" = { fg = "#94b0a6" }
"type.enum" = { fg = "#94b0a6" }
"type.enum.variant" = { fg = "#d4d4d4" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#d4d4d4", fg = "#181818" }
"ui.cursor.match" = { fg = "#d4d4d4", modifiers = ["bold"] }
"ui.linenr" = { fg = "#343434" }
"ui.linenr.select" = { fg = "#d4d4d4", modifiers = ["bold"] }
"ui.menu" = { bg = "#151515", fg = "#d4d4d4" }
"ui.menu.scroll" = { bg = 2171169, fg = 3421236 }
"ui.menu.selected" = { bg = "#2e2e2e" }
"ui.popup" = { bg = "#151515", fg = "#7b8292" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#151515", fg = "#969696" }
"ui.statusline.inactive" = { bg = "#151515", fg = "#343434" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#181818", fg = "#d4d4d4" }
"ui.text.focus" = { bg = "#2e2c2a" }
"ui.text.inactive" = { fg = "#a47e47", modifiers = ["italic"] }
"ui.text.info" = { bg = "#151515", fg = "#d4d4d4" }
"ui.virtual.inlay-hint" = { bg = "#2f2e2a", fg = "#fef0ca" }
"ui.window" = { fg = "#131313", modifiers = ["bold"] }
variable = { fg = "#d4d4d4" }
"variable.builtin" = { fg = "#ffcf5b" }
"variable.other.member" = { fg = "#94b0a6" }
"variable.parameter" = { fg = "#ffdd34" }
warning = { fg = "#ffcf5b" }

[palette]
bg = "#181818"
bg_dark = "#151515"
bg_float = "#151515"
bg_highlight = "#212121"
bg_popup = "#151515"
bg_search = "#ff66b0"
bg_sidebar = "#151515"
bg_statusline = "#151515"
bg_visual = "#2e2c2a"
black = "#131313"
blue = "#d4d4d4"
blue0 = "#504946"
blue1 = "#949cb1"
blue2 = "#0db9d7"
blue3 = "#94b0a6"
blue4 = "#7aa2f7"
blue5 = "#d4d4d4"
blue6 = "#b4f9f8"
blue7 = "#394b70"
border = "#131313"
border_highlight = "#7b8292"
comment = "#a47e47"
cyan = "#d4d4d4"
dark3 = "#545c7e"
dark5 = "#d4d4d4"
"delta.add" = "#2a585f"
"delta.delete" = "#7a3131"
"diff.add" = "#242922"
"diff.change" = "#2e250d"
"diff.delete" = "#2a1919"
"diff.text" = "#644d0e"
error = "#f15050"
fg = "#d4d4d4"
fg_dark = "#969696"
fg_float = "#d4d4d4"
fg_gutter = "#343434"
fg_sidebar = "#969696"
"git.add" = "#82d458"
"git.change" = "#ffcf5b"
"git.delete" = "#e46565"
"git.ignore" = "#545c7e"
"gitSigns.add" = "#82d458"
"gitSigns.change" = "#ffcf5b"
"gitSigns.delete" = "#e46565"
gray = "#4d8d97"
green = "#7abf47"
green1 = "#d4d4d4"
green2 = "#41a6b5"
hint = "#fef0ca"
info = "#0db9d7"
magenta = "#ffcf5b"
magenta2 = "#5c5542"
magenta3 = "#ff66b0"
magenta4 = "#ff007c"
orange = "#d4d4d4"
purple = "#ffcf5b"
red = "#ffcf5b"
red1 = "#f15050"
teal = "#fef0ca"
terminal_black = "#414868"
todo = "#d4d4d4"
warning = "#ffcf5b"
yellow = "#ffcf5b"
yellow1 = "#ffdd34"