[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# highlight = "path/to/tmTheme"

cwd = { fg = "#888888", italic = true }

# Hovered
hovered         = { bg = "#dbdbdb" }
preview_hovered = { bg = "#dbdbdb" }

# Find
find_keyword  = { fg = "#ececec", bg = "#606060", bold = true }
find_position = { fg = "#07879d", bg = "#162325", bold = true }

# Marker
marker_copied   = { fg = "#606060", bg = "#606060" }
marker_cut      = { fg = "#765b00", bg = "#765b00" }
marker_marked   = { fg = "#765b00", bg = "#765b00" }
marker_selected = { fg = "#606060", bg = "#606060" }

# Tab
tab_active   = { fg = "#606060", bg = "#dbdbdb" }
tab_inactive = { fg = "#c2c2c2", bg = "#e7e7e7" }
tab_width    = 1

# Count
count_copied   = { fg = "#606060", bg = "#38919f" }
count_cut      = { fg = "#606060", bg = "#c22727" }
count_selected = { fg = "#606060", bg = "#b2a49e" }
# Border
border_symbol = "│"
border_style  = { fg = "#666c7a" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#c2c2c2", bg = "#c2c2c2" }

# Mode
mode_normal = { fg = "#ececec", bg = "#606060", bold = true }
mode_select = { fg = "#ececec", bg = "#765b00", bold = true }
mode_unset  = { fg = "#ececec", bg = "#765b00", bold = true }

# Progress
progress_label  = { fg = "#888888", bold = true }
progress_normal = { fg = "#e7e7e7" }
progress_error  = { fg = "#765b00" }

# Permissions
permissions_t = { fg = "#606060" }
permissions_r = { fg = "#765b00" }
permissions_w = { fg = "#765b00" }
permissions_x = { fg = "#53852f" }
permissions_s = { fg = "#a1a6c5" }

[select]
border   = { fg = "#666c7a" }
active   = { fg = "#606060",  bg = "#d1cbc4" }
inactive = { fg = "#606060" }

# Input
[input]
border   = { fg = "#07879d" }
title    = {}
value    = { fg = "#765b00" }
selected = { bg = "#d1cbc4" }

# Completion
[completion]
border   = { fg = "#07879d" }
active   = { fg = "#606060", bg = "#d1cbc4" }
inactive = { fg = "#606060" }

# Tasks
[tasks]
border  = { fg = "#666c7a" }
title   = {}
hovered = { fg = "#606060", bg="#d1cbc4" }

# Which
[which]
cols = 3
mask            = { bg = "#ececec" }
cand            = { fg = "#606060" }
rest            = { fg = "#606060" }
desc            = { fg = "#765b00" }
separator       = "  "
separator_style = { fg = "#836437" }

# Notify
[notify]
title_info  = { fg = "#07879d" }
title_warn  = { fg = "#765b00" }
title_error = { fg = "#765b00" }

# Help
[help]
on      = { fg = "#53852f" }
run     = { fg = "#765b00" }
hovered = { bg = "#d1cbc4" }
footer  = { fg = "#606060", bg = "#e7e7e7" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#765b00" },

	# Media
	{ mime = "{audio,video}/*", fg = "#765b00" },

	# Archives
	{ mime = "application/*zip", fg = "#765b00" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#765b00" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#606060" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#765b00" },

	# Special files
	{ name = "*", is = "orphan", bg = "#765b00" },
	{ name = "*", is = "exec"  , fg = "#53852f" },

	# Fallback
	{ name = "*/", fg = "#606060" }
]
    