[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# highlight = "path/to/tmTheme"

cwd = { fg = "#969696", italic = true }

# Hovered
hovered         = { bg = "#212121" }
preview_hovered = { bg = "#212121" }

# Find
find_keyword  = { fg = "#151515", bg = "#d4d4d4", bold = true }
find_position = { fg = "#0db9d7", bg = "#17282b", bold = true }

# Marker
marker_copied   = { fg = "#d4d4d4", bg = "#d4d4d4" }
marker_cut      = { fg = "#ffcf5b", bg = "#ffcf5b" }
marker_marked   = { fg = "#ffcf5b", bg = "#ffcf5b" }
marker_selected = { fg = "#d4d4d4", bg = "#d4d4d4" }

# Tab
tab_active   = { fg = "#d4d4d4", bg = "#212121" }
tab_inactive = { fg = "#343434", bg = "#181818" }
tab_width    = 1

# Count
count_copied   = { fg = "#d4d4d4", bg = "#41a6b5" }
count_cut      = { fg = "#d4d4d4", bg = "#f15050" }
count_selected = { fg = "#d4d4d4", bg = "#504946" }
# Border
border_symbol = "│"
border_style  = { fg = "#7b8292" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#343434", bg = "#343434" }

# Mode
mode_normal = { fg = "#151515", bg = "#d4d4d4", bold = true }
mode_select = { fg = "#151515", bg = "#ffcf5b", bold = true }
mode_unset  = { fg = "#151515", bg = "#ffcf5b", bold = true }

# Progress
progress_label  = { fg = "#969696", bold = true }
progress_normal = { fg = "#181818" }
progress_error  = { fg = "#ffcf5b" }

# Permissions
permissions_t = { fg = "#d4d4d4" }
permissions_r = { fg = "#ffcf5b" }
permissions_w = { fg = "#ffcf5b" }
permissions_x = { fg = "#7abf47" }
permissions_s = { fg = "#414868" }

[select]
border   = { fg = "#7b8292" }
active   = { fg = "#d4d4d4",  bg = "#2e2c2a" }
inactive = { fg = "#d4d4d4" }

# Input
[input]
border   = { fg = "#0db9d7" }
title    = {}
value    = { fg = "#ffcf5b" }
selected = { bg = "#2e2c2a" }

# Completion
[completion]
border   = { fg = "#0db9d7" }
active   = { fg = "#d4d4d4", bg = "#2e2c2a" }
inactive = { fg = "#d4d4d4" }

# Tasks
[tasks]
border  = { fg = "#7b8292" }
title   = {}
hovered = { fg = "#d4d4d4", bg="#2e2c2a" }

# Which
[which]
cols = 3
mask            = { bg = "#151515" }
cand            = { fg = "#d4d4d4" }
rest            = { fg = "#d4d4d4" }
desc            = { fg = "#ffcf5b" }
separator       = "  "
separator_style = { fg = "#a47e47" }

# Notify
[notify]
title_info  = { fg = "#0db9d7" }
title_warn  = { fg = "#ffcf5b" }
title_error = { fg = "#ffcf5b" }

# Help
[help]
on      = { fg = "#7abf47" }
run     = { fg = "#ffcf5b" }
hovered = { bg = "#2e2c2a" }
footer  = { fg = "#d4d4d4", bg = "#181818" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#ffcf5b" },

	# Media
	{ mime = "{audio,video}/*", fg = "#ffcf5b" },

	# Archives
	{ mime = "application/*zip", fg = "#ffcf5b" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ffcf5b" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#d4d4d4" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#ffcf5b" },

	# Special files
	{ name = "*", is = "orphan", bg = "#ffcf5b" },
	{ name = "*", is = "exec"  , fg = "#7abf47" },

	# Fallback
	{ name = "*/", fg = "#d4d4d4" }
]
    